name: Hash from a fork

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@c7d749a2d57b4b375d1ebcd17cfbfb60c676f18e

      - name: list files
        run: ls -la
        
